In [15]:
import torch
import numpy as np

def get_an_input(seed0=0, seed1=1, n_class=2, n_sample=3, n_feature=5):

    torch.manual_seed(seed0)

    A = torch.autograd.Variable(torch.rand(n_feature, n_class), requires_grad=True)

    torch.manual_seed(seed1)

    x = torch.autograd.Variable(torch.rand(n_sample, n_feature), requires_grad=False)

    return A, x
 

def test(cross_entropy2, n_class=2, n_sample=4, n_feature=5):

    seed0, seed1 = np.random.randint(100), np.random.randint(100)

    loss = torch.nn.CrossEntropyLoss()

    A0, x0 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    A1, x1 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])

 
    loss0 = loss(x1.matmul(A1), target)

    loss1 = cross_entropy2(torch.softmax(x0.matmul(A0), dim=1), target)

 
    loss0.backward()

    loss1.backward()


    print(loss0, '\n')

    print(loss1, '\n')

    print(A0.grad, '\n')

    print(A1.grad, '\n')

 

def cross_entropy2(logits, target):

    #################### Start your code ######################
    m = target.shape[0]
    log_likelihood = -torch.log(logits[range(m), target])
    loss = torch.sum(log_likelihood, dim=0)/m
    
    print('m has a shape of:', m)
    print("cross_entropy2 loss", loss)

    #################### End your code #######################

    return loss

In [16]:
test(cross_entropy2)

m has a shape of: 4
cross_entropy2 loss tensor(0.6111, grad_fn=<DivBackward0>)
tensor(0.6111, grad_fn=<NllLossBackward>) 

tensor(0.6111, grad_fn=<DivBackward0>) 

tensor([[-0.2064,  0.2064],
        [-0.3126,  0.3126],
        [-0.1520,  0.1520],
        [-0.2946,  0.2946],
        [-0.1418,  0.1418]]) 

tensor([[-0.2064,  0.2064],
        [-0.3126,  0.3126],
        [-0.1520,  0.1520],
        [-0.2946,  0.2946],
        [-0.1418,  0.1418]]) 



In [5]:
n_class = 2
n_sample = 4
n_feature= 5

seed0, seed1 = np.random.randint(100), np.random.randint(100)
A0, x0 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
print(f'A0 has a shape of: {A0.shape}')     # (feature x class)
print(f'x0 has a shape of: {x0.shape}')     # (sample x feature)
target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])  # (1, batch)
logits = torch.softmax(x0.matmul(A0), dim = 1)  # (batch_size, num of class)

logits, logits.shape

A0 has a shape of: torch.Size([5, 2])
x0 has a shape of: torch.Size([4, 5])


(tensor([[0.3033, 0.6967],
         [0.5266, 0.4734],
         [0.3083, 0.6917],
         [0.2766, 0.7234]], grad_fn=<SoftmaxBackward>),
 torch.Size([4, 2]))

In [13]:
m = target.shape[0]
print(logits[range(m), target])
log_likelihood = -torch.log(logits[range(m), target])
log_likelihood

tensor([0.6967, 0.4734, 0.3083, 0.2766], grad_fn=<IndexBackward>)


tensor([0.3614, 0.7478, 1.1767, 1.2852], grad_fn=<NegBackward>)

In [14]:
loss = torch.sum(log_likelihood, dim=0)/m
loss, (0.3614+0.7478+1.1767+1.2852)/4

(tensor(0.8928, grad_fn=<DivBackward0>), 0.8927749999999999)