In [9]:
import torch
import numpy as np

def get_an_input(seed0=0, seed1=1, n_class=2, n_sample=3, n_feature=5):

    torch.manual_seed(seed0)

    A = torch.autograd.Variable(torch.rand(n_feature, n_class), requires_grad=True)

    torch.manual_seed(seed1)

    x = torch.autograd.Variable(torch.rand(n_sample, n_feature), requires_grad=False)

    return A, x
 

def test(cross_entropy2, n_class=2, n_sample=4, n_feature=5):

    seed0, seed1 = np.random.randint(100), np.random.randint(100)

    loss = torch.nn.CrossEntropyLoss()

    A0, x0 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    A1, x1 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])

 
    loss0 = loss(x1.matmul(A1), target)

    loss1 = cross_entropy2(torch.softmax(x0.matmul(A0), dim=1), target)

 
    loss0.backward()

    loss1.backward()


    print(loss0, '\n')

    print(loss1, '\n')

    print(A0.grad, '\n')

    print(A1.grad, '\n')

 

def cross_entropy2(logits, target):

    #################### Start your code ######################
    m = target.shape[0]
    log_likelihood = -torch.log(logits[range(m), target])
    loss = torch.sum(log_likelihood, dim=0)/m
    
    print('m has a shape of:', m)
    print("cross_entropy2 loss", loss)

    #################### End your code #######################

    return loss

def cross_entropy3(logits, target):
    
    m = target.shape[0]
    output= []
    
    logitnp = logits.cpu().detach().numpy()
    for index in range(m):
        output.append(logitnp[index, target[index]])
    print(output)
    
    tmp = np.array(output)   
    
    loss = torch.softmax(torch.FloatTensor(tmp))
    
    print("ce3:" ,loss)
        
    #loss = torch.sum(-torch.log(torch.FloatTensor(tmp)), dim= 0)/m
    
    return loss

In [10]:
test(cross_entropy2)

m has a shape of: 4
cross_entropy2 loss tensor(0.6576, grad_fn=<DivBackward0>)
tensor(0.6576, grad_fn=<NllLossBackward>) 

tensor(0.6576, grad_fn=<DivBackward0>) 

tensor([[ 0.1306, -0.1306],
        [ 0.0450, -0.0450],
        [ 0.0045, -0.0045],
        [ 0.0035, -0.0035],
        [ 0.0551, -0.0551]]) 

tensor([[ 0.1306, -0.1306],
        [ 0.0450, -0.0450],
        [ 0.0045, -0.0045],
        [ 0.0035, -0.0035],
        [ 0.0551, -0.0551]]) 



In [11]:
n_class = 2
n_sample = 4
n_feature= 5

seed0, seed1 = np.random.randint(100), np.random.randint(100)
A0, x0 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
print(f'A0 has a shape of: {A0.shape}')     # (feature x class)
print(f'x0 has a shape of: {x0.shape}')     # (sample x feature)
target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])  # (1, batch)
logits = torch.softmax(x0.matmul(A0), dim = 1)  # (batch_size, num of class)
print('target:', target)

logits, logits.shape

A0 has a shape of: torch.Size([5, 2])
x0 has a shape of: torch.Size([4, 5])
target: tensor([0, 1, 1, 1])


(tensor([[0.4617, 0.5383],
         [0.5610, 0.4390],
         [0.5320, 0.4680],
         [0.4610, 0.5390]], grad_fn=<SoftmaxBackward>),
 torch.Size([4, 2]))

In [12]:
m = target.shape[0]
print(logits[range(m), target])
log_likelihood = -torch.log(logits[range(m), target])
log_likelihood

tensor([0.4617, 0.4390, 0.4680, 0.5390], grad_fn=<IndexBackward>)


tensor([0.7728, 0.8232, 0.7593, 0.6181], grad_fn=<NegBackward>)

In [13]:
loss = torch.sum(log_likelihood, dim=0)/m
loss, (0.3614+0.7478+1.1767+1.2852)/4

(tensor(0.7434, grad_fn=<DivBackward0>), 0.8927749999999999)