6.  When the number of class is 2, please modifiy your cross-entropy function, so that it can accept soft labels.  (In this case, the larget is no longer 0 or 1, it's a float number from 0 to 1 and stands for the probability of being from class 1. )

In [1]:
import torch
import numpy as np

def get_an_input(seed0=0, seed1=1, n_class=2, n_sample=3, n_feature=5):

    torch.manual_seed(seed0)

    A = torch.autograd.Variable(torch.rand(n_feature, n_class), requires_grad=True)

    torch.manual_seed(seed1)

    x = torch.autograd.Variable(torch.rand(n_sample, n_feature), requires_grad=False)

    return A, x
 

def test(cross_entropy2, soft_cross_entropy, n_class=2, n_sample=4, n_feature=5):

    seed0, seed1 = np.random.randint(100), np.random.randint(100)

    loss = torch.nn.CrossEntropyLoss()

    A0, x0 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    A1, x1 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
    
    A2, x2 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])
    

    loss0 = loss(x1.matmul(A1), target)

    loss1 = cross_entropy2(torch.softmax(x0.matmul(A0), dim=1), target)
    
    s_target = torch.tensor([np.random.dirichlet(np.ones(n_class),size=1) for _ in range(n_sample)])
    soft_target = torch.squeeze(s_target, 1)
     
#     loss2 = soft_cross_entropy(torch.softmax(x2.matmul(A2), dim=1), soft_target)

 
    loss0.backward()

    loss1.backward()
    
#     loss2.backward()
    


    print(loss0, '\n')

    print(loss1, '\n')
    
#     print(loss2, '\n')

    print(A0.grad, '\n')

    print(A1.grad, '\n')
    
#     print(A2.grad, '\n')
    

def soft_cross_entropy(logits, target):
    #### start your code #####
    m = target.shape[0]
    soft_log_likelihood = -torch.log(torch.sum(logits * target, dim=1))
    soft_loss = torch.sum(soft_log_likelihood, dim=0)/m
    
    return soft_loss
    
    ### End your code   ##### 

def cross_entropy2(logits, target):
    

    #################### Start your code ######################
    m = target.shape[0]
    log_likelihood = -torch.log(logits[range(m), target])
    loss = torch.sum(log_likelihood, dim=0)/m
    
    print('m has a shape of:', m)
    print("cross_entropy2 loss", loss)

    #################### End your code #######################

    return loss

In [2]:
test(cross_entropy2, soft_cross_entropy)

m has a shape of: 4
cross_entropy2 loss tensor(0.7175, grad_fn=<DivBackward0>)
tensor(0.7175, grad_fn=<NllLossBackward>) 

tensor(0.7175, grad_fn=<DivBackward0>) 

tensor([[-0.0995,  0.0995],
        [-0.1342,  0.1342],
        [-0.0376,  0.0376],
        [ 0.1504, -0.1504],
        [ 0.0516, -0.0516]]) 

tensor([[-0.0995,  0.0995],
        [-0.1342,  0.1342],
        [-0.0376,  0.0376],
        [ 0.1504, -0.1504],
        [ 0.0516, -0.0516]]) 



In [3]:
# (tensor([1, 1, 0, 0]),
#  tensor([[0.4736, 0.6136],
#          [0.0121, 0.0396],
#          [0.5674, 0.2538],
#          [0.5338, 0.6093],
#          [0.7162, 0.6043]], requires_grad=True),
#  tensor([[0.5695, 0.0047, 0.9303, 0.7257, 0.8295],
#          [0.7683, 0.0600, 0.1453, 0.2924, 0.5292],
#          [0.1466, 0.8305, 0.3579, 0.7729, 0.4808],
#          [0.2147, 0.0352, 0.9872, 0.6413, 0.4447]]),
#  tensor([[0.5621, 0.4379],
#          [0.4934, 0.5066],
#          [0.5161, 0.4839],
#          [0.5695, 0.4305]], grad_fn=<SoftmaxBackward>))

In [4]:
n_class = 2
n_sample = 4
n_feature= 5

seed0, seed1 = np.random.randint(100), np.random.randint(100)
A1, x1 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])
logits = torch.softmax(x1.matmul(A1), dim=1)

target, A1, x1, logits

(tensor([1, 1, 0, 1]),
 tensor([[0.2364, 0.2266],
         [0.8005, 0.1692],
         [0.2650, 0.7720],
         [0.1282, 0.7452],
         [0.8045, 0.6357]], requires_grad=True),
 tensor([[0.7644, 0.3751, 0.0751, 0.5308, 0.9660],
         [0.2770, 0.3372, 0.8910, 0.4304, 0.3090],
         [0.3993, 0.5183, 0.0927, 0.3571, 0.9848],
         [0.3928, 0.9554, 0.3048, 0.2989, 0.3510]]),
 tensor([[0.5104, 0.4896],
         [0.3895, 0.6105],
         [0.5573, 0.4427],
         [0.5811, 0.4189]], grad_fn=<SoftmaxBackward>))

In [5]:
m = target.shape[0]
log_likelihood = -torch.log(logits[range(m), target])
loss = torch.sum(log_likelihood, dim=0)/target.shape[0]
log_likelihood, loss

(tensor([0.7142, 0.4934, 0.5847, 0.8701], grad_fn=<NegBackward>),
 tensor(0.6656, grad_fn=<DivBackward0>))

In [6]:
s_target = torch.tensor([np.random.dirichlet(np.ones(n_class),size=1) for _ in range(n_sample)])
soft_target = torch.squeeze(s_target, 1)
soft_target, soft_target.shape

(tensor([[0.8465, 0.1535],
         [0.4143, 0.5857],
         [0.1658, 0.8342],
         [0.8105, 0.1895]], dtype=torch.float64),
 torch.Size([4, 2]))

In [7]:
A2, x2 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
A2, A2.shape, x2.shape

(tensor([[0.2364, 0.2266],
         [0.8005, 0.1692],
         [0.2650, 0.7720],
         [0.1282, 0.7452],
         [0.8045, 0.6357]], requires_grad=True),
 torch.Size([5, 2]),
 torch.Size([4, 5]))

In [8]:
torch.softmax(x2.matmul(A2), dim=1)

tensor([[0.5104, 0.4896],
        [0.3895, 0.6105],
        [0.5573, 0.4427],
        [0.5811, 0.4189]], grad_fn=<SoftmaxBackward>)

In [9]:
m = soft_target.shape[0]
soft_log_likelihood = torch.sum(logits * soft_target, dim=1)
soft_loss = torch.sum(soft_log_likelihood, dim=0)/soft_target.shape[0]
soft_log_likelihood, soft_loss

(tensor([0.5072, 0.5189, 0.4617, 0.5504], dtype=torch.float64,
        grad_fn=<SumBackward1>),
 tensor(0.5096, dtype=torch.float64, grad_fn=<DivBackward0>))

In [10]:
soft_log_likelihood

tensor([0.5072, 0.5189, 0.4617, 0.5504], dtype=torch.float64,
       grad_fn=<SumBackward1>)

In [11]:
torch.sum(logits * soft_target, dim=0)

tensor([1.1568, 0.8814], dtype=torch.float64, grad_fn=<SumBackward1>)

In [22]:
target

(tensor([[0.3456, 0.6544],
         [0.9930, 0.0070],
         [0.1190, 0.8810],
         [0.3765, 0.6235]], dtype=torch.float64),
 tensor([1, 1, 0, 0]))