6.  When the number of class is 2, please modifiy your cross-entropy function, so that it can accept soft labels.  (In this case, the larget is no longer 0 or 1, it's a float number from 0 to 1 and stands for the probability of being from class 1. )

In [7]:
import torch
import numpy as np

def get_an_input(seed0=0, seed1=1, n_class=2, n_sample=3, n_feature=5):

    torch.manual_seed(seed0)

    A = torch.autograd.Variable(torch.rand(n_feature, n_class), requires_grad=True)

    torch.manual_seed(seed1)

    x = torch.autograd.Variable(torch.rand(n_sample, n_feature), requires_grad=False)

    return A, x
 

def test(cross_entropy2, soft_cross_entropy, n_class=2, n_sample=4, n_feature=5):

    seed0, seed1 = np.random.randint(100), np.random.randint(100)

    loss = torch.nn.CrossEntropyLoss()

    A0, x0 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    A1, x1 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
    
    A2, x2 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)

    target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])
    
    s_target = torch.tensor([np.random.dirichlet(np.ones(n_class),size=1) for _ in range(n_sample)])
    soft_target = torch.squeeze(s_target, 1)
    

    loss0 = loss(x1.matmul(A1), target)

    loss1 = cross_entropy2(torch.softmax(x0.matmul(A0), dim=1), target)
     
    loss2 = soft_cross_entropy(torch.softmax(x2.matmul(A2), dim=1), soft_target)

 
    loss0.backward()

    loss1.backward()
    
    loss2.backward()
    


    print(loss0, '\n')

    print(loss1, '\n')
    
    print(loss2, '\n')

    print(A0.grad, '\n')

    print(A1.grad, '\n')
    
    print(A2.grad, '\n')
    

def soft_cross_entropy(logits, target):
    #### start your code #####
    m = target.shape[0]
    soft_log_likelihood = -torch.log(torch.sum(logits * target, dim=1))
    soft_loss = torch.sum(soft_log_likelihood, dim=0)/m
    
    return soft_loss
    
    ### End your code   ##### 

def cross_entropy2(logits, target):
    

    #################### Start your code ######################
    m = target.shape[0]
    log_likelihood = -torch.log(logits[range(m), target])
    loss = torch.sum(log_likelihood, dim=0)/m
    
    print('m has a shape of:', m)
    print("cross_entropy2 loss", loss)

    #################### End your code #######################

    return loss

In [8]:
test(cross_entropy2, soft_cross_entropy)

m has a shape of: 4
cross_entropy2 loss tensor(0.7291, grad_fn=<DivBackward0>)
tensor(0.7291, grad_fn=<NllLossBackward>) 

tensor(0.7291, grad_fn=<DivBackward0>) 

tensor(0.6525, dtype=torch.float64, grad_fn=<DivBackward0>) 

tensor([[ 0.0757, -0.0757],
        [-0.0180,  0.0180],
        [ 0.0284, -0.0284],
        [ 0.0474, -0.0474],
        [-0.0200,  0.0200]]) 

tensor([[ 0.0757, -0.0757],
        [-0.0180,  0.0180],
        [ 0.0284, -0.0284],
        [ 0.0474, -0.0474],
        [-0.0200,  0.0200]]) 

tensor([[-0.0618,  0.0618],
        [-0.0382,  0.0382],
        [-0.0905,  0.0905],
        [-0.0665,  0.0665],
        [-0.1048,  0.1048]]) 



In [9]:
n_class = 2
n_sample = 4
n_feature= 5

seed0, seed1 = np.random.randint(100), np.random.randint(100)
A1, x1 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
target = torch.tensor([np.random.randint(n_class) for _ in range(n_sample)])
logits = torch.softmax(x1.matmul(A1), dim=1)

target, A1, x1, logits

(tensor([0, 0, 0, 1]),
 tensor([[0.7865, 0.3806],
         [0.7820, 0.4943],
         [0.0335, 0.7917],
         [0.8909, 0.8513],
         [0.4682, 0.0496]], requires_grad=True),
 tensor([[0.8674, 0.2262, 0.0158, 0.3520, 0.0753],
         [0.8784, 0.1758, 0.3905, 0.2213, 0.5736],
         [0.0050, 0.1305, 0.8398, 0.9041, 0.9417],
         [0.9396, 0.1421, 0.1628, 0.6087, 0.6335]]),
 tensor([[0.6108, 0.3892],
         [0.5890, 0.4110],
         [0.4583, 0.5417],
         [0.6429, 0.3571]], grad_fn=<SoftmaxBackward>))

In [11]:
m = target.shape[0]
log_likelihood = -torch.log(logits[range(m), target])
loss = torch.sum(log_likelihood, dim=0)/target.shape[0]
log_likelihood, loss

(tensor([0.4930, 0.5293, 0.7802, 1.0298], grad_fn=<NegBackward>),
 tensor(0.7081, grad_fn=<DivBackward0>))

In [12]:
s_target = torch.tensor([np.random.dirichlet(np.ones(n_class),size=1) for _ in range(n_sample)])
soft_target = torch.squeeze(s_target, 1)
soft_target.shape

torch.Size([4, 2])

In [13]:
A2, x2 = get_an_input(seed0, seed1, n_class, n_sample, n_feature)
A2, A2.shape, x2.shape

(tensor([[0.7865, 0.3806],
         [0.7820, 0.4943],
         [0.0335, 0.7917],
         [0.8909, 0.8513],
         [0.4682, 0.0496]], requires_grad=True),
 torch.Size([5, 2]),
 torch.Size([4, 5]))

In [14]:
torch.softmax(x2.matmul(A2), dim=1)

tensor([[0.6108, 0.3892],
        [0.5890, 0.4110],
        [0.4583, 0.5417],
        [0.6429, 0.3571]], grad_fn=<SoftmaxBackward>)

In [15]:
m = soft_target.shape[0]
soft_log_likelihood = torch.sum(logits * soft_target, dim=1)
soft_loss = torch.sum(soft_log_likelihood, dim=0)/soft_target.shape[0]
soft_log_likelihood, soft_loss

(tensor([0.5333, 0.5426, 0.4904, 0.4953], dtype=torch.float64,
        grad_fn=<SumBackward1>),
 tensor(0.5154, dtype=torch.float64, grad_fn=<DivBackward0>))

In [16]:
soft_log_likelihood

tensor([0.5333, 0.5426, 0.4904, 0.4953], dtype=torch.float64,
       grad_fn=<SumBackward1>)

In [17]:
torch.sum(logits * soft_target, dim=0)

tensor([1.4258, 0.6359], dtype=torch.float64, grad_fn=<SumBackward1>)